version: "3"

services:
  todo-api:
    build: ./api
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
  todo-frontend:
    build: ./todo-frontend
    volumes:
      - ./todo-frontend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 8080:8080
    command: npm run start


      
  
