version: "3"

services:
  todo-api:
    build: ./api
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - todo-db
    networks:
      - net-todo-app
    hostname: todo-api
    environment:
    - NODE_ENV=prod
  app:
    build: ./app
    volumes:
      - ./app:/home/app
      - /home/app/node_modules
    ports:
      - 8080:8080
    command: npm run start
    logging:
      driver: none
    networks:
      - net-todo-app
    hostname: todo-front
  todo-db:
    image: 'mongo'
    container_name: todo-mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
    networks:
      - net-todo-app

networks:
  net-todo-app:


      
  
